spring:
   flyway:
      enabled: true
      locations: classpath:db/migration

   jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
   sql:
    init:
      mode: always
   datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: sA#259979148307
logging:
   level:
    org:
      springframework:
        security: DEBUG
